name: Backup Juejin Aphorism Daily

on:
  schedule:
    # 每天北京时间 8 点执行 (UTC 0点)
    - cron: '00 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get aphorism
        run: |
          response=$(curl -s https://api.juejin.cn/growth_api/v1/get_coder_calendar)
          # sentence=$(echo "$response" | jq -r '.data.aphorism')
          # echo "$(date +'%Y-%m-%d'): $sentence" >> README.md

          # 查找并提取 aphorism 字段的值
          aphorism=$(echo "$response" | grep -Po '"aphorism": *\K"[^"]*"')

          # 查找并提取 should_or_not 字段的值
          should_or_not=$(echo "$response" | grep -Po '"should_or_not": *\K"[^"]*"')

          # 去除双引号
          aphorism=$(echo "$aphorism" | tr -d '"')
          should_or_not=$(echo "$should_or_not" | tr -d '"')

          echo "| $(date +'%Y-%m-%d') | $should_or_not | $aphorism |" >> backup/aphorism.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update aphorism.md"
          branch: main
